#version 450

layout(constant_id = 0) const uint WG_SIZE = 256;
layout(local_size_x_id = 0) in;

layout(set = 0, binding = 0) readonly buffer BufSrc { float src[]; };
layout(set = 0, binding = 1) writeonly buffer BufDst { float dst[]; };

layout(push_constant) uniform PushConstants {
    uint n;
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < n) {
        dst[idx] = src[idx];
    }
}
